### ISSUE TITLE
Cannot open settings

### ISSUE THREAD

**Issue by atamax** [UbadahJ/QReader#29]
Nothing happens after I try to open the settings menu, I just want to change the theme to night mode. Everything else is working fine. I'm running Android 7.0 Nougat currently, is this the reason the settings menu is not working?

**Comment by UbadahJ** [comment]
@atamax Glad that everything is working fine for you. The setting menu is not implemented at the moment and that option is just a placeholder. 

Currently dark mode is controlled by system dark mode which is only available from Android 9.0+. Currently the setting with application theme override is planned and in backlog.
